### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by yuxinPenny** [GoekeLab/xpore#109]
I came up with following error while running the spore diffmod. The nanopolish eventalign and data-prep output seems no problem. Can you give some clues?
 
Traceback (most recent call last):
  File "/home/yuxin/miniconda3/bin/xpore", line 8, in <module>
    sys.exit(main())
  File "/home/yuxin/miniconda3/lib/python3.8/site-packages/xpore/scripts/xpore.py", line 67, in main
    options.func(options)
  File "/home/yuxin/miniconda3/lib/python3.8/site-packages/xpore/scripts/diffmod.py", line 169, in diffmod
    data_dict[(condition_name,run_name)] = ujson.loads(json_str) # A data dict for each gene.
ValueError: Expected object or value

PS. code to for nanopolish event align and data prep

/home/yuxin/minimap2-2.17_x64-linux/minimap2 -ax map-ont \
/data/yuxin/2021Fall/Reference/HomoSapiens/gencode.v29.transcripts_simplified.fa \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/fastq/HMEC_WT_fastq.tar.gz > \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.sam -t 6

samtools view -b \
-S /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.sam > \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam

# sort
samtools sort \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam \
-o /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam

# index
samtools index \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam.bai

cd /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/fastq/workspace/pass
find -maxdepth 5 -name "*.fastq"|xargs -i awk \
'{if(NR%4 == 1){print ">" substr($0, 2)}}{if(NR%4 == 2){print}}' {} |cat > \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result/HMEC_WT_reads.fasta

# index
/home/yuxin/nanopolish/nanopolish index -d /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/fast5_single_pass \
/data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result/HMEC_WT_reads.fasta

# event align
/home/yuxin/nanopolish/nanopolish eventalign \
--reads /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result/HMEC_WT_reads.fasta \
--bam /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/bam/HMEC_WT_t.bam \
--genome /data/yuxin/2021Fall/Reference/HomoSapiens/gencode.v29.transcripts_simplified.fa \
--scale-events > /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result/reads-ref.eventalign.txt \
-t 5

xpore dataprep \
--eventalign /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result/reads-ref.eventalign.txt \
--out_dir /data/yuxin/2021Fall/HomoSapiens/HMEC/HMEC_WT/xpore_result \
--n_processes 6

**Comment by yuukiiwa** [comment]
Hi @yuxinPenny,

I am so sorry for the delayed reply (I thought someone else answered the question as I see there's a comment already). Do you mind sharing the `config.yml` file you used for running `xpore diffmod`, please? 
Thanks!

Best wishes,
Yuk Kei
