### ISSUE TITLE
Are the initial data-prep steps now in line with m6anet? 

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/xpore#114]
I recently updated xpore and rerunning the tool on my files. Is the data prep files now compatible with m6anet to run and get the actual m6A calls rather than differential modified sites.

**Comment by yuukiiwa** [comment]
Hi @callumparr,

The `xpore dataprep` outputs are not compatible with `m6anet-run_inference`, so you will have to run the `m6anet-dataprep` for detecting m6A sites with `m6anet-run_inference`.
Thanks!

Best wishes,
Yuk Kei

**Comment by callumparr** [comment]
Thank you
