### ISSUE TITLE
--n_processes errors xpore diffmod

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/xpore#119]
Using multiple processes to speed up processing time there is some issue from h5py and accessing or writing out some files. 

I installed xpore using pip install under new environment with python 3.8.

Having prepared the data with `xpore dataprep`  with `--genome` flag already then ran the `xpore diffmod` part on my replicates and two conditions

```
#!/bin/bash
# Set source of conda install
source miniconda3/etc/profile.d/conda.sh

conda activate xpore

export baseDir=/analysisdata/rawseq/bcl/callum

xpore diffmod --n_processes 24 --config xpore_diffmod_output/Male_SPF_young_vs_old_config_20211217.yml --save_models
```
Config file
```
Data:
    Male_SPF_young:
        Rep1: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day2_03_DRS
        Rep2: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day3_06_DRS
        Rep3: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day4_09_DRS

    Male_SPF_old:
        Rep1: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day3_09_DRS
        Rep2: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day7_01_DRS
        Rep3: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day7_02_DRS

out: xpore_diffmod_output/Male_SPF_young_vs_old_2

criteria:
    readcount_min: 15
    readcount_max: 1000

method:
    prefiltering:
        method: t-test
        threshold: 0.1
    max_iters: 500
    stopping_criterial: 0.0001

```
After it processes some genes it will output the following error per process that is having the issue. Same error comes running interactively on the cluster instead of using qsub.

```
Process Consumer-3:
Traceback (most recent call last):
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/diffmod.py", line 63, in execute
    io.save_models_to_hdf5(models,out_paths['model_filepath'])
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/diffmod/io.py", line 110, in save_models_to_hdf5
    model_file = h5py.File(model_filepath, 'w')
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/h5py/_hl/files.py", line 196, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 116, in h5py.h5f.create
OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
```

If I remove the `--save_models` flag it will proceed without error. Is there something we can do with the models after this step?

**Comment by yuukiiwa** [comment]
Hi @callumparr,

Thank you for reporting the bug! Yes, `--save_models` right now only works with `--n_processes 1`, and we will try to fix the bug soon. There is not much to do with the models after running `xpore diffmod` (we run it without `--save_models` most of the time).
Thank you!

Best wishes,
Yuk Kei

**Comment by callumparr** [comment]
Thank you for the reply and thats a relief as I ran without saving

**Comment by Xiao-lin-Liu** [comment]
hello, I was wondering if this could not be used directly on mouse cells as the methylation knockout model used for xpore is human cells? I'm just checking in politely as I also have a batch of mouse tissue samples that need to be processed

**Comment by AndreaYCT** [comment]
Hi, @yuukiiwa, 

I have encountered error like this:
`Traceback (most recent call last):
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/site-packages/xpore/scripts/helper.py", line 113, in run
    result = self.task_function(*next_task_args,self.locks)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/site-packages/xpore/scripts/diffmod.py", line 63, in execute
    io.save_models_to_hdf5(models,out_paths['model_filepath'])
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/site-packages/xpore/diffmod/io.py", line 110, in save_models_to_hdf5
    model_file = h5py.File(model_filepath, 'w')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ohpc/Taiwania3/pkg/biology/xpore/xpore_v2.1/lib/python3.12/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
BlockingIOError: [Errno 11] Unable to synchronously create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')`

Does this affect result table? When it's running in HPC, does it become endless running?

Thanks!

Andrea


> Using multiple processes to speed up processing time there is some issue from h5py and accessing or writing out some files.
> 
> I installed xpore using pip install under new environment with python 3.8.
> 
> Having prepared the data with `xpore dataprep` with `--genome` flag already then ran the `xpore diffmod` part on my replicates and two conditions
> 
> ```
> #!/bin/bash
> # Set source of conda install
> source miniconda3/etc/profile.d/conda.sh
> 
> conda activate xpore
> 
> export baseDir=/analysisdata/rawseq/bcl/callum
> 
> xpore diffmod --n_processes 24 --config xpore_diffmod_output/Male_SPF_young_vs_old_config_20211217.yml --save_models
> ```
> 
> Config file
> 
> ```
> Data:
>     Male_SPF_young:
>         Rep1: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day2_03_DRS
>         Rep2: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day3_06_DRS
>         Rep3: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day4_09_DRS
> 
>     Male_SPF_old:
>         Rep1: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day3_09_DRS
>         Rep2: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day7_01_DRS
>         Rep3: /analysisdata/rawseq/bcl/callum/Mouse_aging/dataprep/Day7_02_DRS
> 
> out: xpore_diffmod_output/Male_SPF_young_vs_old_2
> 
> criteria:
>     readcount_min: 15
>     readcount_max: 1000
> 
> method:
>     prefiltering:
>         method: t-test
>         threshold: 0.1
>     max_iters: 500
>     stopping_criterial: 0.0001
> ```
> 
> After it processes some genes it will output the following error per process that is having the issue. Same error comes running interactively on the cluster instead of using qsub.
> 
> ```
> Process Consumer-3:
> Traceback (most recent call last):
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/helper.py", line 113, in run
>     result = self.task_function(*next_task_args,self.locks)
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/scripts/diffmod.py", line 63, in execute
>     io.save_models_to_hdf5(models,out_paths['model_filepath'])
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/xpore/diffmod/io.py", line 110, in save_models_to_hdf5
>     model_file = h5py.File(model_filepath, 'w')
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/h5py/_hl/files.py", line 424, in __init__
>     fid = make_fid(name, mode, userblock_size,
>   File "/home/callum/miniconda3/envs/xpore/lib/python3.8/site-packages/h5py/_hl/files.py", line 196, in make_fid
>     fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 116, in h5py.h5f.create
> OSError: Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
> ```
> 
> If I remove the `--save_models` flag it will proceed without error. Is there something we can do with the models after this step?
