### ISSUE TITLE
dataprep ERROR

### ISSUE THREAD

**Issue by zzf77** [GoekeLab/xpore#137]
Hi developer,
I'm trying to using the practice demo data downloaded from https://zenodo.org/record/5103099/files/demo.tar.gz, and I have successfully installed the latest version of xpore.
When I came to the step of dataprep following the help and manual, I kept getting the same ERROR and could not proceed.
My working directory:
~/demo/data/HEK293T-METTL3-KO-rep1 

Using the command "xpore-dataprep -h" we can see the usage information, which tell us the "summary" is required:
(apptest) [zzf@ser1 ~]$ xpore-dataprep -h
usage: xpore-dataprep [-h] --eventalign EVENTALIGN --summary SUMMARY --out_dir
                      OUT_DIR [--ensembl ENSEMBL] [--species SPECIES]
                      [--genome] [--n_processes N_PROCESSES]
                      [--readcount_max READCOUNT_MAX] [--resume]

While in [https://xpore.readthedocs.io/en/latest/quickstart.html](url), i don't see the "summary" command.

The running command:
xpore-dataprep \
--eventalign /home/dragon/Database/zzf/demo/demo/data/HEK293T-METTL3-KO-rep1/nanopolish/eventalign.txt \
--summary /home/dragon/Database/zzf/demo/demo/data/HEK293T-METTL3-KO-rep1/nanopolish/summary.txt \
--gtf_or_gff /home/dragon/Database/zzf/demo/demo/demo.gtf  \
--transcript_fasta /home/dragon/Database/zzf/demo/demo/demo.fa \
--out_dir dataprep \
--genome

And then came this ERROR:
xpore-dataprep: error: unrecognized arguments: --gtf_or_gff /home/dragon/Database/zzf/demo/demo/demo.gtf --transcript_fasta /home/dragon/Database/zzf/demo/demo/demo.fa

If i use "xpore dataprep', the tool will come with this：
Command 'xpore' not found,did you mean:

It would be grateful if you could give me some advice on solving this problem. Thanks for developing this nice tool.

**Comment by yuukiiwa** [comment]
Hi @zzf77,

The most updated version of `xpore` (v2.1) no longer has the `--summary` command, so it will be great if you can update `xpore` to `v2.1`.

Thank you!

Best wishes,
Yuk Kei
