### ISSUE TITLE
Dataprep error

### ISSUE THREAD

**Issue by rania-o** [GoekeLab/xpore#140]
Hi,

I'm trying to use Xpore to detect modifications on one transcript (440 bp).
but I got this error while running the command dataprep :

xpore dataprep --eventalign nanopolish/psi0_transcrit_oligo.eventalign.txt --out_dir dataprep_results --transcript_fasta ../transcript_oligo.fasta

"""
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk_split['line_length'] = np.array(lines)
"""

-Here is the head of my eventalign.txt file : 
contig	position	reference_kmer	read_index	strand	event_index	event_level_mean	event_stdv	event_length	model_kmer	model_mean	model_stdv	standardized_level
dystro-oligo	0	GCCAA	0	t	4	78.27	1.380	0.01328GCCAA	73.26	2.11	1.75
dystro-oligo	1	CCAA	0	t	5	92.55	2.484	0.00465CCAA	87.19	3.02	1.31
dystro-oligo	1	CCAA	0	t	6	95.85	1.139	0.00465CCAA	87.19	3.02	2.12
dystro-oligo	2	CAA	0	t	7	98.24	2.083	0.00564CAA	105.72	2.68	-2.06
dystro-oligo	2	CAA	0	t	8	96.94	3.260	0.00598CAA	105.72	2.68	-2.42
dystro-oligo	3	AA	0	t	9	122.06	1.616	0.00299AA	108.90	2.68	3.63
dystro-oligo	4	A	0	t	10	119.61	3.024	0.01295A108.90	2.68	2.95
dystro-oligo	4	A	0	t	11	101.06	3.389	0.00996A108.90	2.68	-2.16

I don't have a GTF file for this sample since it's synthesized, the GTF file is optional right ?

Thank you,
Rania

**Comment by yuukiiwa** [comment]
Hi Rania,

The following several lines are not an error (you can check your `dataprep` folder whether the inputs are empty):
```
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
chunk_split['line_length'] = np.array(lines)
```
If you're not using the `--genome` option you don't need to provide `--transcript_fasta ../transcript_oligo.fasta`, so the following command should be good:
```
xpore dataprep --eventalign nanopolish/psi0_transcrit_oligo.eventalign.txt --out_dir dataprep_results
```
Thanks!

Best wishes,
Yuk Kei

**Comment by rania-o** [comment]
Hi Yuk Kei,

Thank you for your answer. 
I thought it was an error because my dataprep folder contains the results but there is just "NaN".
Here is the head of my json file (it's all NaN):
```
{"dystro-oligo":{"2":{"GCCAA":[NaN,NaN,NaN,NaN,NaN]},"3":{"CCAA":[NaN,NaN,NaN,Na
N,NaN,NaN,NaN,NaN,NaN]},"4":{"CAA":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
NaN]},"5":{"AA":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]},"6":{"A":[NaN,NaN,NaN,NaN,NaN
,NaN,NaN,NaN]},"8":{"AA":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Na
N,NaN,NaN,NaN,NaN,NaN]},"9":{"A":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Na
N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]},"11":{"A
AACC":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN]},"12":{"AACC":[NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
aN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
```
Also when I run the diff_mod with these results I got this error :

```
1 ids to be testing ...
Traceback (most recent call last):
  File "/usr/local/bin/xpore", line 33, in <module>
    sys.exit(load_entry_point('xpore==2.1', 'console_scripts', 'xpore')())
  File "/usr/local/lib/python3.6/dist-packages/xpore-2.1-py3.6.egg/xpore/scripts/xpore.py", line 67, in main
    options.func(options)
  File "/usr/local/lib/python3.6/dist-packages/xpore-2.1-py3.6.egg/xpore/scripts/diffmod.py", line 169, in diffmod
    data_dict[(condition_name,run_name)] = ujson.loads(json_str) # A data dict for each gene.
ValueError: Expected object or value
```
This is what my log file contains :
```
dystro-oligo: True.
Total 1 transcripts.
--- SUCCESSFULLY FINISHED --- 
```

and this is my read count file :
```
idx,n_reads
dystro-oligo,998
```

I have more than 20 000 reads mapped to my reference, Is there a coverage filter or something that makes the number of reads drop to 998 ?

Thanks,
Rania
