### ISSUE TITLE
Regulate minimum coverage manually ？

### ISSUE THREAD

**Issue by Peng-Lingwei** [GoekeLab/xpore#143]
Hello！
Thanks for such an excellent software, I have some doubts about diffmod.table. When I checked the  Colum9 and Column10 of diffmod.table, I found that the minimum coverage is 15. I am not sure whether I can select the minimum coverage manually (I am trying to get a lower coverage), because I did not find the relative parameter.
![image](https://user-images.githubusercontent.com/103977020/163911950-65709077-b9c9-46e7-84aa-85ee3ac19ca3.png)

**Comment by yuukiiwa** [comment]
Hi @Peng-Lingwei,

You will have to add the following to your `config.yml` file:
```
criteria:
    readcount_min: <integer less than 15>
```
You can find more information about the config.yml file from here:
https://xpore.readthedocs.io/en/latest/configuration.html

Thanks!

Best wishes,
Yuk Kei
