### ISSUE TITLE
eventalign.txt file size 

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/xpore#149]
Hi, for the data preparation, I followed xpore docs.
My data is direct RNA and used gencode transcriptome fasta file for the reference.
And received 2T eventalign.txt files for each sample.
how big of an eventalign.txt file should I expect? 
Is it normal to receive this big file size for xpore dataprep input and if so, how can I manage it?

**Comment by yuukiiwa** [comment]
Hi @sunsetyerin,

Yes, if your sample is generated from PromethION then the size of a `eventalign.txt` file can range between 1-4T from our experience, and `xpore` can handle large files.

Best wishes,
Yuk Kei

**Comment by sunsetyerin** [comment]
Hi @yuukiiwa, thanks for the suggestion,
if I feed the eventalign.tar.gz file to xpore dataprep, will it work?

**Comment by yuukiiwa** [comment]
Hi @sunsetyerin,

No, it won't work. You will have to uncompressed it to `eventalign.txt` to feed it to `xpore dataprep`
Thanks!

Best wishes,
Yuk Kei
