### ISSUE TITLE
reference files inquiry

### ISSUE THREAD

**Issue by sunsetyerin** [GoekeLab/xpore#150]
Hi, can you please guide me on which reference file to use for direct human RNA? 

For nanopolish aligning, should the reference file be genome or transcriptome?
Also, for xpore data preparation, wonder which fasta and gtf files to use.
It's just so confusing which ref files to use because of the empty xpore dataprep results.
Can you let me know exactly which ref file and its link to download? 

Thanks,

**Comment by yuukiiwa** [comment]
Hi @sunsetyerin,

You will have to do transcriptome alignment with nanopolish. We suggest using the ENSEMBL fasta and gtf files.

ENSEMBL human cDNA fasta: 
http://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
ENSEMBL human gtf: 
http://ftp.ensembl.org/pub/release-106/gtf/homo_sapiens/Homo_sapiens.GRCh38.106.gtf.gz

Thanks!

Best wishes,
Yuk Kei
