### ISSUE TITLE
output table description

### ISSUE THREAD

**Issue by zzf77** [GoekeLab/xpore#153]
Hi developer
I have successfully run my data with xpore and got the results like that:
![image](https://user-images.githubusercontent.com/101631038/187871694-dad46b09-0957-4b32-9868-fd8daedf5366.png)
I want to get the gene name from the chromosome and its position by bedtools. So the start and end position of each gene were necessary. Like the first line, the position 1981 refers to the T，which is the middle base of GATGG. So the start position of the first gene is 1979, and the end position of that is 1983. Is my understanding correct? Or is there any other good way to get the gene name from this result? I am looking forward to your reply.
Best wishes

**Comment by yuukiiwa** [comment]
HI @zzf77,

Sorry for the delayed reply! xpore does have an option to get the gene names, where you will have to use the `--genome`, `--transcript_fasta`, and `--gtf_or_gff` flags. Here is [an example command for extracting the genome coordinates](https://xpore.readthedocs.io/en/latest/quickstart.html):
```
xpore dataprep \
--eventalign nanopolish/eventalign.txt \
--gtf_or_gff ../../demo.gtf \
--transcript_fasta ../../demo.fa \
--out_dir dataprep \
--genome
```

Thanks!

Best wishes,
Yuk Kei

**Comment by zzf77** [comment]
Thank you four your reply! So, is my understanding about the position correct? The position number refers to the middle of kmer.
Thank you!

**Comment by yuukiiwa** [comment]
Hi @zzf77.

Yes, the position is the middle nucleotide of the kmer.
Thanks!

Best wishes,
Yuk Kei
