### ISSUE TITLE
dRNA-Seq kit and FLO cell ID

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/xpore#154]
Hi there,
Thank you for developing this immensely helpful tool for analysis of ONT dRNA-Seq data.
I would appreciate knowing the sequencing kit and FLO cell ID used for the below data used in the xPore paper in Nature Biotechnology, which I need to run guppy for base calling.
HEK293T-KO-rep 1
HEK293T-KO-rep 2
HEK293T-KO-rep 3
HEK293T-WT-rep 1
HEK293T-WT-rep 2
HEK293T-WT-rep 3

Thank you for your kind consideration.
Kind regards
Reza

**Comment by yuukiiwa** [comment]
Hi @rezarahman12,

Here are the information on the FLO cell ID and sequencing kit for the samples:
HEK293T-KO-rep 1: FLO-MIN106D, SQK-RNA001
HEK293T-KO-rep 2: FLO-MIN106D, SQK-RNA002
HEK293T-KO-rep 3: FLO-MIN106D, SQK-RNA002
HEK293T-WT-rep 1: FLO-MIN106D, SQK-RNA001
HEK293T-WT-rep 2: FLO-MIN106D, SQK-RNA002
HEK293T-WT-rep 3: FLO-MIN106, SQK-RNA002

Thanks!

Best wishes,
Yuk Kei

**Comment by rezarahman12** [comment]
Thank you for your kind reply.
