### ISSUE TITLE
HEK293T data fast5 untar problem

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/xpore#158]
Hi,

I have downloaded the fast5 files of the xpore paper from ENA. HEK293T-Mettl3-KO-rep2.tar.gz is downloaded using the below command-

wget ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4708848/HEK293T-Mettl3-KO-rep2.tar.gz

then I ran the command tar: -xvzf HEK293T-Mettl3-KO-rep2.tar.gz

After running the above, I saw the directory-
 "**20190805_Sho_M3-1**" was created which contains another directory "**M3-1**". then I check inside M3-1 another directory "**20190805_0636_MN19344_FAK28957_6cdec02f**". Then I check another directory "**fast5**", which contains all .fast5 files.

I checked .e file of job submission which showed the below error:

gzip: stdin: invalid compressed data--crc error
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Could you please tell how to solve this problem?
Kind regards
Reza

**Comment by yuukiiwa** [comment]
Hi Reza (@rezarahman12),

Thanks for reporting this! We will upload a non-corrupted version of the file to ENA soon.

Best wishes,
Yuk Kei
