### ISSUE TITLE
eventalignment and bas fast5 file 

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/xpore#159]
Dear xpore team,

I have downloaded xpore paper's dRNA-seq data consisting of fast5 (ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4706254/HEK293T-Mettl3-KO-rep1.tar.gz) and basecalled fastq files (ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR470/ERR4706158/HEK293T-Mettl3-KO-rep1.fastq.gz) from . Then, I ran a job using nanopolish with the below script.

The output is also given below for your kind consideration. I will seek your opinion is it a normal output since I see a lot of bad fast5 file.
...
[readdb] indexing /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fast5_dir/ko-rep1/20181121_1017_21112018_Sho_METTI3_10/fast5/221
**[readdb] num reads: 1490210, num reads with path to fast5: 1113644
fast5 files could not be located for 376566 reads
[post-run summary] total reads: 981058, unparseable: 0, qc fail: 40158, could not calibrate: 1979, no alignment: 719, bad fast5: 337754**

The script of the job is given below:

#!/bin/bash
#PBS -A UQ-QBI
#PBS -l select=1:ncpus=10:mem=50GB
#PBS -e /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1
#PBS -o /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1
#PBS -l walltime=72:00:00
#PBS -N nanopol_ko-rep1

cd $PBS_O_WORKDIR

module load nanopolish/0.14.0

nanopolish index -d /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fast5_dir/20181121_1017_21112018_Sho_METTI3_10/fast5 /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fastq_dir/ko-rep1/HEK293T-Mettl3-KO-rep1.fastq.gz
nanopolish eventalign --reads /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fastq_dir/ko-rep1/HEK293T-Mettl3-KO-rep1.fastq.gz
--bam /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/align/ko-rep1/aligned.sort.bam
--genome /scratch/project_mnt/S0077/xPore/Homo_sapiens.GRCh38.cdna.all.fa
--signal-index
--scale-events
--summary /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/summary.txt
--threads 32 > /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/nanopol/ko-rep1/eventalign.txt

I do highly appreciate your time, help and cooperation.
Kind regards
Reza

**Comment by yuukiiwa** [comment]
Dear Reza (I will tag you here @rezarahman12),

It will be great if you try `gunzip` `HEK293T-Mettl3-KO-rep1.fastq.gz` first before indexing:
```
gunzip HEK293T-Mettl3-KO-rep1.fastq.gz

nanopolish index -d /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fast5_dir/20181121_1017_21112018_Sho_METTI3_10/fast5 /scratch/project_mnt/S0077/xPore/rawdata/xpore_data/fastq_dir/ko-rep1/HEK293T-Mettl3-KO-rep1.fastq
```

Thanks!

Best wishes,
Yuk Kei

**Comment by rezarahman12** [comment]
Thank you for your kind feedback. @yuukiiwa

**Comment by rezarahman12** [comment]
Hi Yuk Kei, (@yuukiiwa )
Thank you the problem resolved.
Best regards
Reza
