### ISSUE TITLE
output of diffmod and xpore post processing

### ISSUE THREAD

**Issue by rezarahman12** [GoekeLab/xpore#168]
Dear xPore team,

The output of xPore and xpore post-prcoessing table does not have chromosome column.

I have given the screenshot of my output file. Could you please tell me why the chromosome file is missing?

![image](https://user-images.githubusercontent.com/110575883/204135353-69b73cee-c1a7-4ec3-90dd-cad273b1f18f.png)
Thank you for your time and help.
Best regards
Reza

**Comment by yuukiiwa** [comment]
Hi Reza (@rezarahman12),

The current version of `xPore` doesn't output a chromosome column. We can implement that for the next release.

Thanks!

Best wishes,
Yuk Kei

**Comment by rezarahman12** [comment]
Thanks, Yuk Kei for letting us know. Yes, that will be an excellent option if you kindly add that feature. 

For now, could you please help me get the chromosomes of those genes identified?
Kind regards
Reza

**Comment by yuukiiwa** [comment]
Hi Reza (@rezarahman12),

I have implemented a function to include the chromosome and gene id through `xpore postprocessing` in the `add_chr_gname` branch, you can try running this with the following:

1. download `xpore-add_chr_gname` branch: https://github.com/GoekeLab/xpore/archive/refs/heads/add_chr_gname.zip
2. after unzipping the folder then go into the folder with `cd xpore-add_chr_gname` and install `xpore` with the following (add `sudo` if necessary):
```
python3 setup.py install
```
3. Ran xpore postprocessing with the following:
```
xpore postprocessing --diffmod_dir [diffmod output directory] --gtf_or_gff [gtf file used in dataprep] --genome
```

Thanks!

Best wishes,
Yuk Kei

**Comment by rezarahman12** [comment]
Hi Yuk Kei (@yuukiiwa )
Thank you so much for your big help. It worked well.
Many thanks
Reza
