### ISSUE TITLE
diffmod output files empty

### ISSUE THREAD

**Issue by anaesco** [GoekeLab/xpore#169]
Hi there, 

I have successfully ran the data preparation from raw reads and the xpore preprocess steps, but once I ran xpore diffmod, the files are empty. This is the command line argument: 
$ xpore diffmod --config IGF2_SCRAM_cell_config_nofilt.yml
Using the signal of unmodified RNA from /home/carter-balaj/miniconda3/lib/python3.9/site-packages/xpore/diffmod/model_kmer.csv
0 ids to be testing ...

Any guidance is greatly appreciated thanks!! 

Attached are also the files from the preprocess.
[data.log](https://github.com/GoekeLab/xpore/files/10296959/data.log)

[data.log](https://github.com/GoekeLab/xpore/files/10296958/data.log)

**Comment by yuukiiwa** [comment]
Hi @anaesco,

Your first `data.log` first use the genome reference instead of the transcriptome reference while your second `data.log` file uses the transcriptome reference which is correct. However, xpore dataprep cannot match to the reference as the first column of 
 the eventalign.txt file may look like the following:
```
ENST00000416931.1|ENSG00000225972.1|OTTHUMG00000002338.1|OTTHUMT00000006720.1|MTND1P23-201|MTND1P23|372|unprocessed_pseudogene|
```
while the reference transcript id looks like the following:
```
ENST00000416931.1
```

One thing you will have to do is to modified the first column of the eventalign.txt file to match the reference (here is an example python script (not tested)):
```
import sys
fn=sys.argv[1]
file=open(fn,'r')
outfile=open('new'+fn,'w')
for ln in file:
 ln=ln.split('\t')
 first_col=ln[0].split('|')[0]
 newln=[first_col]+ln[1:]
 outfile.write('\t'.join(newln))
outfile.close()
```

Thanks!

Best wishes,
Yuk Kei

**Comment by anaesco** [comment]
Hi there! 

Thanks so much for responding. I figured it was the first column in the eventalign file since I was reading the closed issues section and someone had a similar issue. 
However, I am having a hard time editing this first column since the files that I have are over 500gb in size. 
I just tried testing the python script that you provided, butt unfortunately the file does not open afterwards and it crashes the text editor app. 
I have limited proficiency in python, so I was wondering what else I could do to edit this first column in the eventalign file. 


Thanks! 



script.py 

`import sys
fn=sys.argv[1]
file=open(fn,'r')
outfile=open('new'+fn,'w')
for ln in file:
	ln=ln.split('\t')
	first_col=ln[0].split('|')[0]
	newln=[first_col]+ln[1:]
	outfile.write('\t'.join(newln))
outfile.close()`

**Comment by anaesco** [comment]
As a final question, 

Is there any documentation as to which code was used to produce the results (data visualization)? Any guidance would be great! thank you!!

**Comment by yuukiiwa** [comment]
Hi @anaesco,

We have a tutorial that will be included in ONT's EPI2ME-LABS soon, which includes some visualization codes. It is attached below:
https://drive.google.com/file/d/1xEddN-1mFXeKsaxqCmLt4q-lVvMhL_A4/view?usp=share_link

Thanks!

Best wishes,
Yuk Kei
