### ISSUE TITLE
data-prep genome mapping for species other than homo sapiens

### ISSUE THREAD

**Issue by sbultmann** [GoekeLab/xpore#17]
Hi!
Thank you for this great tool. It seems to be working flawlessly in my hands. 
I only have a small comment:
At the moment dataprep.py only accepts an ensmbl release number and no species. 
When using data mapped to non-human genome, this causes the transgene to gene mapping to fail silently resulting in an empty data.json.
I think it could be an easy fix (if I haven't missed anything ;-) ) by adding another option to the 
`get_args():`. 

Something like:
`required.add_argument('--species', dest='species', help='species for ensembl gene-transcript mapping.', default='homo_sapiens)`

in `def main():` adding:
`ensembl_species = args.species`

and changing line 516 to:
`ensembl = EnsemblRelease(ensembl_version, ensembl_species)`

Anyway thanks a lot for this tool and the preprint!

**Comment by ploy-rukawa** [comment]
Thank you very much Sebastian. I'll include it in the next release soon.

**Comment by ploy-np** [comment]
I fixed this and updated it to version 0.5.1 already. Thank you again for your suggestion.
