### ISSUE TITLE
The scope of application of the xpore

### ISSUE THREAD

**Issue by zzf77** [GoekeLab/xpore#178]
Hi @yuukiiwa.
Thank you for your tool, it's very nice. I have finished running my programs on human tissues, but I have a question.
Could xpore be used in analysing m6a level in an individual sample, not comparative. I found a paper(DOI: https://doi.org/10.1128/mbio.03702-21) say xpore can analyse individual and comparative samples, but I don't find the approach for individual.

Thanks!

Best wishes,
zhang zaifeng

**Comment by yuukiiwa** [comment]
Hi @zzf77,

Thanks for your kind words! The tool was developed by @ploy-np, so I can't take the credit! :)

To clarify, our lab has two tools for RNA modification detection:
`xpore` uses a comparative approach for detecting whether sites in a sample is differentially modified compared to another sample, so one can detect m6A by comparing a WT sample and a METTL3 knockout sample
`m6anet` takes in an individual sample and predict whether the site is an m6A, which is the individual approach.

Thanks!

Best wishes,
Yuk Kei
