### ISSUE TITLE
error in datapre step

### ISSUE THREAD

**Issue by huawen-poppy** [GoekeLab/xpore#184]
Hello, thanks for your great tool!

Recently I am trying to run xpore on my data, however, there is an error stating that:
`  File "pandas/_libs/lib.pyx", line 2411, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "114.817,115.635,109.092,117.816,123.814,102.277" at position 0`

could you please help me fix this problem? Thank you very much!

**Comment by yuukiiwa** [comment]
Hi @huawen-poppy,

Do you mind sharing the command you use and `head` all the inputs (`eventalign.txt`, `gtf`, and `fasta`) you use, please?

Thanks!

Best wishes,
Yuk Kei

**Comment by huawen-poppy** [comment]
Thank you for your response! 
I was using the command `xpore dataprep --eventalign eventalign.txt --gtf_or_gff CC7.gtf --transcript_fasta aip.genome_models.no_isoforms.no_duplication.mRNA.fa --out_dir ./output --n_process 32`
I figured out the error sourced form the eventalign file, in which I have an extra column containing the strings '114.817,115.635,109.092,117.816,123.814,102.277'. Now I deleted the extra column. But it comes with another error:
`/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()
/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()
/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()
/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()
/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chunk_split['line_length'] = np.array(lines)`
  
 The header of eventalign.txt file is 
  <img width="1853" alt="image" src="https://github.com/GoekeLab/xpore/assets/70507602/b08ecd90-30b9-4173-8eeb-2deb00dc5fc5">

the header of the gtf file is:
<img width="1860" alt="image" src="https://github.com/GoekeLab/xpore/assets/70507602/6e9d8e11-8c68-487e-b421-cb04f60b38d6">

the header of the fasta file is:
![image](https://github.com/GoekeLab/xpore/assets/70507602/d248a3da-9c70-4e1d-9e98-af1a01da5029)
 

Could you please help me sovle this problem? Thanks!

**Comment by yuukiiwa** [comment]
Hi @huawen-poppy,

To convert the transcript position to genome position, you will have to include the `--genome` flag too:
```
xpore dataprep --eventalign eventalign.txt --gtf_or_gff CC7.gtf --transcript_fasta aip.genome_models.no_isoforms.no_duplication.mRNA.fa --genome --out_dir ./output --n_process 32
```

Do you mind sharing the full error message from `xpore diffmod`, please?

Thanks!

Best wishes,
Yuk Kei

**Comment by huawen-poppy** [comment]
Hi. Thanks for your reply! I am still running the xpore diffmod process. So far there is no error messages. The head of the diffmod.table looks like:
![image](https://github.com/GoekeLab/xpore/assets/70507602/2b619f7b-11ad-4924-94b8-e5b6b7d9bd4e)

Do you think I should cancel the current job and run the xpore dataprep process with adding flag --genome?

**Comment by yuukiiwa** [comment]
Hi @huawen-poppy,

If you don't need to convert the transcript coordinates to genomic coordinates, then you don't need the `--genome` , `--gtf_or_gff`, and `--transcript_fasta` flags.

I have just noticed that the sequences of your fasta file are not capitalized. If you need transcript-to-genomic coordinate conversion, you can try capitalizing them.

Thanks!

Best wishes,
Yuk Kei

**Comment by AndreaYCT** [comment]
Hi, 

I have encountered " PerformanceWarning" as well. I still can have eventalign.index generated.
Does it affect result? 

Thanks!

Andrea


> Thank you for your response! I was using the command `xpore dataprep --eventalign eventalign.txt --gtf_or_gff CC7.gtf --transcript_fasta aip.genome_models.no_isoforms.no_duplication.mRNA.fa --out_dir ./output --n_process 32` I figured out the error sourced form the eventalign file, in which I have an extra column containing the strings '114.817,115.635,109.092,117.816,123.814,102.277'. Now I deleted the extra column. But it comes with another error: `/home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance. pos_end += eventalign_result.loc[index]['line_length'].sum() /home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance. pos_end += eventalign_result.loc[index]['line_length'].sum() /home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance. pos_end += eventalign_result.loc[index]['line_length'].sum() /home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance. pos_end += eventalign_result.loc[index]['line_length'].sum() /home/zhonh0b/miniconda3/envs/epigenetic/lib/python3.8/site-packages/xpore/scripts/dataprep.py:72: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame. Try using .loc[row_indexer,col_indexer] = value instead
> 
> See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy chunk_split['line_length'] = np.array(lines)`
> 
> The header of eventalign.txt file is <img alt="image" width="1853" src="https://private-user-images.githubusercontent.com/70507602/270103053-b08ecd90-30b9-4173-8eeb-2deb00dc5fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzU0OTYsIm5iZiI6MTcwOTc3NTE5NiwicGF0aCI6Ii83MDUwNzYwMi8yNzAxMDMwNTMtYjA4ZWNkOTAtMzBiOS00MTczLThlZWItMmRlYjAwZGM1ZmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYjk5N2U2OTNlMTJmNjUwNjIzOTcwMDkyZjlkYmQ1MTQ2NzY4NzRiOTM1YzE3ZDlmZThhMzg0NzhiYjhkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1G2kRWJtNQ_NnMWsv2I3tIa1ODdPyXJm8nhtDSYFWvU">
> 
> the header of the gtf file is: <img alt="image" width="1860" src="https://private-user-images.githubusercontent.com/70507602/270103100-6e9d8e11-8c68-487e-b421-cb04f60b38d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzU0OTYsIm5iZiI6MTcwOTc3NTE5NiwicGF0aCI6Ii83MDUwNzYwMi8yNzAxMDMxMDAtNmU5ZDhlMTEtOGM2OC00ODdlLWI0MjEtY2IwNGY2MGIzOGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNDMzZDgwNzkyZjc2NWU3MDJhNTYxYzczZDBmNjM0NWQzYmQ4MWVjM2UxZmI0ZjE1NGFiYmE1NDM2MGI3NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s3_cwVDS9NyoRdxILHlDlx6U1C3gzX5gJO7sJ0To5vA">
> 
> the header of the fasta file is: ![image](https://private-user-images.githubusercontent.com/70507602/270103209-d248a3da-9c70-4e1d-9e98-af1a01da5029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzU0OTYsIm5iZiI6MTcwOTc3NTE5NiwicGF0aCI6Ii83MDUwNzYwMi8yNzAxMDMyMDktZDI0OGEzZGEtOWM3MC00ZTFkLTllOTgtYWYxYTAxZGE1MDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMzMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDY0NzQ4ZTJjMTI0YTQwMjIyNDIzOWJlYTg0ODdmNTYzNmRiNjhkOWM4OGQ1YjcxYjBmMTlhYmUyMjI3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOURJRMdif2Khz0WA52k915mewySa606S5q6Q6d6t-o)
> 
> Could you please help me sovle this problem? Thanks!

**Comment by yuukiiwa** [comment]
Hi @AndreaYCT,

This is warning that doesn't affect the results.

Thanks!

Best wishes,
Yuk Kei
