### ISSUE TITLE
Performance Warning

### ISSUE THREAD

**Issue by nickst85** [GoekeLab/xpore#208]
Hi,

Once I started to indexing my nanopolish eventalign output I got the following Performance Warning error:

.local/lib/python3.9/site-packages/xpore/scripts/dataprep.py:21: PerformanceWarning: indexing past lexsort depth may impact performance.
  pos_end += eventalign_result.loc[index]['line_length'].sum()

Do you know how I can overcome this error?

Thanks in advance,

N

**Comment by yuukiiwa** [comment]
Hi @nickst85.

This is a warning, not an error. It is normal to see this when running `xpore dataprep`.

Thanks!

Best wishes,
Yuk Kei
