### ISSUE TITLE
provide a GTF file for transcript to genome mapping

### ISSUE THREAD

**Issue by mparker2** [GoekeLab/xpore#21]
Hi @ploy-np,

it would make xPore more widely useable if users were able to supply a valid GTF file to perform transcript to genome mapping instead of using pyensembl. It seems that pyensembl is fairly limited - it doesn't even support satellite ensembl servers like ensembl plants or fungi, so I can't use it with Arabidopsis data.

BW
Matt

**Comment by ploy-np** [comment]
Hi @mparker2, 

I've added a feature in xpore-dataprep that users can use their own GTF file to map transcriptome to genome. It's in 'gtf' branch. I'm finding a dataset to test it before I merge with the next release. But it would be very appreciated if you can test this new feature on your own dataset. 

Thank you very much in advance!
