### ISSUE TITLE
xpore dataprep empty output files

### ISSUE THREAD

**Issue by linyan168168** [GoekeLab/xpore#212]
Hi. Thanks for your great tool! Recently I am trying to run xpore on my data, however, the result file was empty. I suspect it may be due to the format of my reference genome. The species is the Sogatella_furcifera, and I think I need your help to convert the format that can be recognized by xpore, this is the genome: http://v2.insect-genome.com/Organism/709,Thank you very much for your sincere help.
<img width="263" alt="1" src="https://github.com/GoekeLab/xpore/assets/130219549/09f40dab-293e-4137-8b69-86d370001ac8">
<img width="392" alt="2" src="https://github.com/GoekeLab/xpore/assets/130219549/f40d222e-9d17-4ac4-a5f4-1ce1b3c99a49">

**Comment by yuukiiwa** [comment]
Hi @linyan168168,

`xpore` supports transcriptome mapping, so instead of the genome fasta file, you can try aligning your data to the CDS fasta file from the page instead.

Thanks!

Best wishes,
Yuk Kei

**Comment by linyan168168** [comment]
Hello, I have aligned the cdna reference genome, but the dataprep is still empty. There are no issues with m6A net dataprep. There is my cDNA reference genome. Could you please take a look and assist me? thank you very much for your sincere help.
[cdna.zip](https://github.com/GoekeLab/xpore/files/14413252/cdna.zip)

**Comment by yuukiiwa** [comment]
Hi @linyan168168,

Do you mind using the following CDS file with the transcriptome cDNA instead? (I downloaded the file by clicking the CDS button in the insect base link):

[Sogatella_furcifera_cds.zip](https://github.com/GoekeLab/xpore/files/14429142/Sogatella_furcifera_cds.zip)


This CDS file is different from the cDNA file you provided.

It will be great if you can share the first 10 lines of the `eventalign.txt` file from aligning to this transcriptome with `head eventalign.txt`

Thanks!

Best wishes,
Yuk Kei

**Comment by linyan168168** [comment]
Dear Yuk Kei,
 Thank you very much for your kind help. In fact, I have aligned it with the CDS file you have sent me, and the result of dataprep is still the same. Below is my eventalign.txt. Thank you again for your kind help.

contig  position        reference_kmer  read_index      strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean      model_stdv      standardized_level
      start_idx       end_idx
Sfur000005.1    243     CGTGT   2       t       515     83.85   1.157   0.00730 CGTGT   91.66   9.69    -0.66   27358   27380
Sfur000005.1    244     GTGTA   2       t       516     89.11   1.728   0.00332 GTGTA   93.81   3.78    -1.03   27348   27358
Sfur000005.1    244     GTGTA   2       t       517     93.65   4.726   0.00398 GTGTA   93.81   3.78    -0.04   27336   27348
Sfur000005.1    245     TGTAT   2       t       518     111.00  2.642   0.00598 TGTAT   110.15  8.56    0.08    27318   27336
Sfur000005.1    245     TGTAT   2       t       519     111.08  3.196   0.01295 TGTAT   110.15  8.56    0.09    27279   27318
Sfur000005.1    245     TGTAT   2       t       520     114.95  1.218   0.00266 TGTAT   110.15  8.56    0.46    27271   27279
Sfur000005.1    246     GTATT   2       t       521     97.50   6.849   0.01096 GTATT   91.86   2.63    1.76    27238   27271
Sfur000005.1    246     GTATT   2       t       522     87.01   1.746   0.00232 GTATT   91.86   2.63    -1.52   27231   27238
Sfur000005.1    247     TATTA   2       t       523     91.66   1.359   0.00564 TATTA   94.35   5.53    -0.40   27214   27231
Sfur000005.1    248     ATTAA   2       t       524     89.74   1.673   0.00598 ATTAA   85.30   2.46    1.49    27196   27214

<img width="1069" alt="78f18fa185df8e74c176ac6bccf7bdc" src="https://github.com/GoekeLab/xpore/assets/130219549/29bf0367-4841-4dda-9b45-c70512699ea0">


Thanks!

Best wishes,
yan lin

**Comment by yuukiiwa** [comment]
Hi Yan Lin (tagging your here @linyan168168),

The eventalign looks fine. Can you give me your `xpore dataprep` commands, please?

If you are using the following parameters `--genome`, '--transcript_fasta', `--gtf_or_gff`, please try removing them.

Thanks!

Best wishes,
Yuk Kei

**Comment by linyan168168** [comment]
Dear Yuk Kei，thank you very much for your help,  this is xpore dataprep
 commands:

nanopolish eventalign --reads ./fastq/CK1.fastq --bam CK1.mapped.bam
--genome cdna.fasta --summary ./nanopolish/summary.txt  --scale-events
--signal-index --threads 16 >eventalign.txt
xpore dataprep \--eventalign nanopolish/eventalign.txt --gtf
../Sogatella_furcifera.gtf --transcript_fasta ../cdna.fasta --out_dir
dataprep --genome

thank you again for your kind help!

Best wishes,

yan lin

Yuk Kei Wan ***@***.***> 于2024年3月4日周一 10:13写道：

**Comment by linyan168168** [comment]
Dear Yuk Kei，thank you very much for your help,  when i remove  the following parameters   --genome, '--transcript_fasta', --gtf_or_gff, and the dataprep is true. In other words, my trouble is solved thanks to your help.

Thank you again for your kind help!
Best wishes,
yan lin

**Comment by yuukiiwa** [comment]
Hi Yan Lin,

No problem! Glad it helps!

Best wishes,
Yuk Kei

**Comment by linyan168168** [comment]
Dear Yuk Kei Wan
I'm so sorry to bother you again. Now, I have get the result file of
diffmod, but in fact, I cannot understand it, I have to seek your help:
kmer diff_mod-rate_cK1_vs-SRBSDv1 pval_cK1_vs-SRBSDv1
z_score-CK1_vs-SRBSDv1 mod-rate-CK1-rep1 mod-rate-SRBSDV1-rep1 coverage
CK1-rep1 coverage SRBSDV1-rep1 mu_unmod mu_mod sigma2_mod conf_mu_unmod
conf_mu_mod mod mod assignment t-test
What do these terms represent respectively? and i have also analyzed the
same data using m6anet. I would also like to ask what is the essential
difference between the XPore result file and the m6anet result file. Thank
you very much for your kind help.

best wishes

yanlin

Yuk Kei Wan ***@***.***> 于2024年3月5日周二 09:02写道：
