### ISSUE TITLE
Question about xpore and Motif Output

### ISSUE THREAD

**Issue by niujiale** [GoekeLab/xpore#220]
Hello,

I am using xpore to analyze example data, but I noticed that some of the motifs in the output do not contain any A or T. Given that xpore is supposed to predict m6A modifications, could you please explain why this is happening?

For example:
  ENSG00000159111,47828510,CCCCC,0.20073062528557367,0.013450862858389518,2.471603447857899,0.5667753285963817,0.366044703310808,89.99999999999999,60.0,62.85211208844585,61.606226759869074,4.420965416151415,0.6351516717735823,0.8573376162243792,0.672942775722758,lower,0.08167266025840088
ENSG00000159111,47828539,ACCCA,-0.20741140693077942,0.010468046905953642,-2.559972424612024,0.28320761960205,0.4906190265328294,90.00000000000006,58.0,66.05653522106958,68.96166260465694,1.5349740243704413,5.3806638091699455,0.9063720573372975,0.19850332451699826,higher,0.07709701263181229
ENSG00000159111,47824296,CCTGT,-0.0804270097000297,0.0016733671467784041,-3.142805983872213,0.9195565973948197,0.9999836070948493,112.99999999999996,61.0,85.58608380337475,88.52494880042461,4.9891199934538335,2.388834204540947,0.6523521809507657,0.5614535889675383,higher,0.01785330776218497
ENSG00000159111,47824220,ACTGT,-0.0032101890749297347,0.8786589583153424,-0.15266944409801814,0.01599340562506029,0.019203594699990025,118.00000000000003,61.0,88.92308228676754,84.77245590825724,2.1117371990254017,10.353776032554013,0.5384777254897615,0.4002115127075413,lower,0.021168573559399783
ENSG00000159111,47823937,CTGAA,-0.08725743869765448,0.05533598451503203,-1.9162287570725993,0.04374894387213015,0.13100638256978464,119.99999999999997,66.00000000000001,112.64541936737662,103.14678074062225,4.936100816279833,25.923278466115775,0.29362398205184204,0.2867379500887991,lower,0.07224256037452804
ENSG00000159111,47831508,TGGCT,0.028393748971304505,0.21394601649192135,1.2427878620919748,0.028424050165171542,3.0301193867038366e-05,53.000000000000014,33.0,113.7950910733345,100.94032777647345,18.065669838173868,133.8849195690182,0.3306973626605687,0.14757532976824558,lower,0.023036583226717842

Thank you!

**Comment by yuukiiwa** [comment]
Hi @niujiale,

`xpore` reports all differentially expressed sites from all 1,024 5-mers (so not DRACH-specific) while `m6anet` reports DRACH sites only.

Thanks!

Best wishes,
Yuk Kei
