### ISSUE TITLE
Inquiry about the result interpretation and m6A level

### ISSUE THREAD

**Issue by kwonej0617** [GoekeLab/xpore#229]
Hi @yuukiiwa 

I wonder if there's a way to get m6A level, which can be defined by the number of m6a-modifying copies out of total number of copies of each transcript?

In addition, could you please explain how you define mod_rate? I read the paper but it is quite hard to understand the concept. 

Thank you!

**Comment by yuukiiwa** [comment]
Hi @kwonej0617,

`xpore` estimates the unmodified and modified distributions. A low `mod_rate` is reported if more current signals of a site are under the unmodified distribution than the modified distribution while a high `mod rate` is reported if more current signals of a site are under the modified distribution than the unmodified distribution.

`xpore` does not output read-level outputs, so we recommend using `m6anet` instead to obtain the proportion of m6A-modified reads in a site. You can combine the results from `m6anet` and `xpore` to select the m6A sites that are differentially modified in the different conditions.

Thanks!

Best wishes,
Yuk Kei
