### ISSUE TITLE
xpore/xpore/diffmod/model_kmer.csv

### ISSUE THREAD

**Issue by pa6774ac-s** [GoekeLab/xpore#31]
Hi!
Cool tool! thanks!
I was wondering how xpore/xpore/diffmod/model_kmer.csv was calculated.
Thanks a lot!

**Comment by ploy-np** [comment]
Hi @pa6774ac-s, 

You're welcome!

The 'model_kmer.csv' file was obtained from Nanopolish output. It contains model_mean and model_std of all 1024 kmers from the Nanopolish model. So, we use them as a reference for signal distributions of unmodified kmers. However, you can create your own reference and give it to xpore. In this case, I will build an API in the future version for ease of use then. Thanks for raising this issue.

**Comment by btrspg** [comment]
Hi @ploy-np ,

I am also interested in the `model_kmer.csv`, as you mentioned which was got from nanopolish output. Do you mean run `nanopolish eventalign` and then statistics the results? May I ask what is the input?

Thanks in advance.
