### ISSUE TITLE
Installation error when i install it with github or pip both

### ISSUE THREAD

**Issue by aman21392** [GoekeLab/xpore#33]
There are error when i using following command to install--- 
1-   python setup.py install
/home/aclab/.local/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing 'v0.5.6' to '0.5.6'
  normalized_version,
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-53616.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

2 -- python3 setup.py install
/home/aclab/.local/lib/python3.6/site-packages/setuptools/dist.py:454: UserWarning: Normalizing 'v0.5.6' to '0.5.6'
  warnings.warn(tmpl.format(**locals()))
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-53623.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

3--  pip install xpore
Collecting xpore
  Could not find a version that satisfies the requirement xpore (from versions: )
No matching distribution found for xpore

Thanks in advance. Please tell me what can i do to install it.

**Comment by ploy-np** [comment]
Hi @aman21392, 

Can you try to create a python environment using python version 3.8?, then install xpore again please?
