### ISSUE TITLE
Not m6A knockout sample.

### ISSUE THREAD

**Issue by litao1503** [GoekeLab/xpore#35]
Hi I am new to bioinformatics - I want to be able to identify m6A but am confused by the knockout/knockdown question in xpore-diffmod.
In some species, m6A knockdown samples are very difficult to obtain.
If we do not m6A knockout sample information, can I continue to use xpore to identify m6a.

Thank you for any guidance on this topic
Regards
Tao

**Comment by ploy-np** [comment]
Hi @litao1503, 
What samples do you have? xPore is a tool to identify differential modifications so it requires at least 2 conditions which are assumably different in modifications. Otherwise, it cannot detect the modification.

**Comment by litao1503** [comment]
Hello @ploy-np ，
Thanks for the response. Here is the more detailed description:
I have four tea plant samples from different growth periods, and I have performed nanopore DRS sequencing on them. I want to compare the m6A modification between four samples. However, all four samples were grown in a natural state, excluding the m6A knockdown samples. I don't know whether it is reliable to use xpore for m6a identification in this case.

**Comment by ploy-np** [comment]
Hi @litao1503,

Sorry for late reply. Yes, you can compare m6A modification between those samples without m6A knockout/knockdown samples.

**Comment by litao1503** [comment]
Thank you so much ploy-np for helping me.
Best Regards
