### ISSUE TITLE
data preparation from raw reads

### ISSUE THREAD

**Issue by q1134269149** [GoekeLab/xpore#36]
Hi,
When I prepared the data for xpore-dataprep, I used the **transcriptomic coordinates**, such as the step of alignment using minimap2. However, I want to  run xpore-dataprep with **genomic coordinates** through add the "**--genome**" parameter. Is there a problem with this? 
Thanks
hqin

**Comment by ploy-np** [comment]
Hi @q1134269149,

No, those are the right steps. You can proceed with that.

**Comment by q1134269149** [comment]
Thank you for your quick reply.
hqin
