### ISSUE TITLE
Last version not available from pypi 

### ISSUE THREAD

**Issue by a-slide** [GoekeLab/xpore#40]
Hi,
I am trying to install the last version (xpore 0.5.6 ) from pip but I got an error message:

```
pip install xpore==0.5.6 
ERROR: Could not find a version that satisfies the requirement xpore==0.5.6 (from versions: 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
ERROR: No matching distribution found for xpore==0.5.6
```

I am not sure what is going on because I can see that the version is present on Pypi
https://pypi.org/project/xpore/0.5.6/

Thanks

**Comment by ploy-np** [comment]
Hi @a-slide,

What python version do you use? Can you try with Python3.8?

**Comment by a-slide** [comment]
I already tried with python 3.8.6 (in a container so not interference with anything else already installed)

**Comment by ploy-np** [comment]
Can you also try with `pip install xpore` for now? It will install the latest version (0.5.6). I will have a look into the version related issue again.

**Comment by a-slide** [comment]
Thanks. Weirdly enough it worked.
I am not sure what is the issue, but for reproducibility it would be nice to get to the bottom of it.

**Comment by callumparr** [comment]
I had to create env using `python=3.8` for pip to install 0.5.6. 

Would it be OK to update the readme for installation?

Also it be useful for others to include the `'--signal-index'` flag when describing how to prepare the eventalign data in the readocuments.

**Comment by a-slide** [comment]
Is the '--signal-index' actually required ?

**Comment by callumparr** [comment]
I do not know but it would not run if I did not generate eventalign with that during the nanopolish dataprep would not run. https://github.com/GoekeLab/xpore/issues/37 this issue seems to state you need to add this as well.

**Comment by ploy-np** [comment]
Yes, --signal-index is required. Thanks, the document was updated.
