### ISSUE TITLE
Run data prep with --genome flag

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/xpore#44]
I was confused if and why --genome flag is needed if we run the initial mapping and eventalign using transcriptome. 

I did not add and now I read another issue here where someone asked if adding --genome flag is wrong. Now I worry all that time I ran it for is wasted. If --genome flag is expected why is it as default? Sorry for so many questions.

A little confused.

**Comment by ploy-np** [comment]
If you want to detect differential modification per **genomic** position, you need to put --genome flag in the xpore-dataprep command. It will model all transcripts aligned to the same genomic position together. But if you want to detect differential modification per **transcriptomic** position, you don't need to use this flag.

**Comment by callumparr** [comment]
Ah I see. Thank you that makes sense.
