### ISSUE TITLE
Guppy software version for base calling

### ISSUE THREAD

**Issue by mmiladi** [GoekeLab/xpore#46]
Hello,

Thanks for providing this tool! 
I was wondering if the version of Guppy can have an impact on the prediction quality and performance. 
I have data called using Guppy 4.0.9 and 3.2.10. Do they expect to work with the latest version of xpore? Would you recommend to re-base call them with a specific version of Guppy to get a reliable performance of m6A predictions? 

Best,
Milad

**Comment by ploy-np** [comment]
Hi @mmiladi,

Sorry for the delayed response. In theory, it shouldn't make much different. In the paper, different Guppy versions were used. However, I recommend to use the same Guppy version across all samples if possible.
