### ISSUE TITLE
Download datasets 

### ISSUE THREAD

**Issue by q1134269149** [GoekeLab/xpore#47]
Hi,
When I download the datasets from PRJEB40872 in NCBI, however, I found a lot of data missing, such as HEK293T-Mett3-KO-rep2, HEK293T-WT-rep2, HEK293T-WT-100-rep1, HEK293T-WT-50-rep1, HEK293T-WT-50-rep2, HEK293T-WT-50-rep3, HEK293T-WT-25-rep2 and so on. Will these missing data continue to be uploaded? In addition, is it convenient to add some descriptive information to the data? For example, what's the difference between data HEK293T-WT-100,  HEK293T-WT-75, HEK293T-WT-50 and HEK293T-WT-25? 
Thank you!
hqin

**Comment by ploy-np** [comment]
We are fixing these data links. Now, you can download the preprocess data files ,which are much smaller, via https://doi.org/10.5281/zenodo.4604945 and https://doi.org/10.5281/zenodo.4587661.

**Comment by q1134269149** [comment]
> We are fixing these data links. Now, you can download the preprocess data files ,which are much smaller, via https://doi.org/10.5281/zenodo.4604945 and https://doi.org/10.5281/zenodo.4587661.

Thanks. I want to download the native fast5 files of HEK293T-Mett3-KO-rep2 and HEK293T-WT-rep2. Can you provide the links for download, thank you.
hqin

**Comment by lwlive** [comment]
In the beginning, I wanted to  try xpore from  the raw fast5 data, but  I  found that  the fast5 files are  100 times bigger than the  fastq files. Therefore   I try to  repeat the analysis  from the  eventalign.txt file. So could you kindly offer me tha eventalign.txt file  with the email (lw_live@163.com).

**Comment by jonathangoeke** [comment]
Hi @lwlive can you post this to the discussion (as a separate entry from your other question)? We can reply there then. Thanks!
