### ISSUE TITLE
qsub batch jobs 

### ISSUE THREAD

**Issue by callumparr** [GoekeLab/xpore#52]
Would it be possible to breakup inputs for xpore-diffmod for qsub batch job. 

Like maybe splitting the reads matching to a gene/transcript?

**Comment by ploy-np** [comment]
xpore was designed to run in parallel across genes. You can specify --n_processes in xpore-diffmod to be the same as what you specify in the qsub command. In this way, xpore will be run in parallel (1 gene per process).

**Comment by callumparr** [comment]
thank you :)
