### ISSUE TITLE
xpore-diffmode error

### ISSUE THREAD

**Issue by al3xMlt** [GoekeLab/xpore#54]
Hello
During processing xpore-diffmode showed following error:

Using the signal of unmodified RNA from /home/amalt/miniconda3/envs/py39/lib/python3.9/site-packages/xpore/diffmod/model_kmer.csv
19620 ids to be testing ...
Traceback (most recent call last):
  File "/home/amalt/miniconda3/envs/py39/bin/xpore-diffmod", line 8, in <module>
    sys.exit(main())
  File "/home/amalt/miniconda3/envs/py39/lib/python3.9/site-packages/xpore/scripts/diffmod.py", line 190, in main
    data_dict[(condition_name,run_name)] = ujson.loads(json_str) # A data dict for each gene.
ValueError: Trailing data

However, xpore has already processed 100 transcripts and then suddenly breaks off in the middle after the 100th transcript.

Thanks in advance!

**Comment by ploy-np** [comment]
Hi @al3xMlt,

Can I ask if the last line of data.log shows "--- SUCCESSFULLY FINISHED ---"?

**Comment by al3xMlt** [comment]
both dataprep files are "--- SUCCESSFULLY FINISHED ---"
but the diffmode data.log doesn't. It ends with the transcript where the error occurred

**Comment by ploy-np** [comment]
Hi @al3xMlt,

Sorry for the slow response!
Do you still have this problem? It seems that data.json for that specific transcript is malformed. Could you search through the file? Or is it possible to share the data.json file by email so that I can explore more about this error?
