### ISSUE TITLE
xpore MinION data access

### ISSUE THREAD

**Issue by sumin5784** [GoekeLab/xpore#59]
Hello :)

 I've been looking for HEK293T cell line nanopore sequencing data, and thank you for the sharing the data.

I have some questions about SRA accession IDs.

There are WT-rep1,2,3 and WT0/25/50/75/100-1,2,3 replicates in accession list. What are the differences between WT and WT0/25/50/75/100?
Also, could you inform me the differences between KO, KD, and KD-Ctrl samples?

I already downloaded HEK293T-WT-rep1,3 and HEK293T-KO-rep1,3. 
WT-rep1 and KO-rep1 are both seemed correct.
But WT/KO-rep3 has 5~6 subfolders and each folder contains only several fast5 files. It seems like it has only a few reads, is there any specific reason for this?

Bests,
Sumin

**Comment by jonathangoeke** [comment]
Hi @sumin5784,
Can you post your question in the discussion forum? 
https://github.com/GoekeLab/xpore/discussions/new
Others will then be able to read the answer as well. Any issue directly related to the xPore implementation feel free to post as an issue.
Thanks!
Jonathan

**Comment by sumin5784** [comment]
Sure!
