### ISSUE TITLE
Prolems about  long mRNA reads mapping

### ISSUE THREAD

**Issue by lwlive** [GoekeLab/xpore#65]
I have read the protocol  in webpage of xpore (https://xpore.readthedocs.io/en/latest/preparation.html). It recomands us to mapping the long mRNA reads  with the following commands "minimap2 -ax **map-ont** -uf -t 3 --secondary=no <MMI> <PATH/TO/FASTQ.GZ> > <PATH/TO/SAM> 2>> <PATH/TO/SAM_LOG>".
I have read the description of the minimap2. It described like following:
  -x STR       preset (always applied before other options; see minimap2.1 for details) []
                 - map-pb/map-ont: PacBio/Nanopore vs reference mapping
                 - ava-pb/ava-ont: PacBio/Nanopore read overlap
                 - asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence
                 - splice: long-read spliced alignment
                 - sr: genomic short-read mapping
I thought it is better to use "splice" for option "-x" in mRNA mapping.  How do you thinks?
Could you give me some suggestion?

**Comment by jonathangoeke** [comment]
Hi @lwlive thanks for the question, can you post this to the [discussions](https://github.com/GoekeLab/xpore/discussions)? I will reply there

**Comment by jonathangoeke** [comment]
answered in #69
