### ISSUE TITLE
DIffmod error 

### ISSUE THREAD

**Issue by Wardale24** [GoekeLab/xpore#92]
Hello,

When running xpore diffmod I get a similar issue to that mentioned in #76 and I was wondering if you resolved that specific issue and if it could be applied to what I am experiencing?

xpore diffmod --config zebrafish_config.yaml --n_processes=32 

From this I get an empty models folder, a 5.2GB diffmod.table and a 354K diffmod.log. The following error was found at the end of the run:

Traceback (most recent call last):
  File "/home/alex/.local/bin/xpore", line 8, in <module>
    sys.exit(main())
  File "/home/alex/.local/lib/python3.8/site-packages/xpore/scripts/xpore.py", line 67, in main
    options.func(options)
  File "/home/alex/.local/lib/python3.8/site-packages/xpore/scripts/diffmod.py", line 169, in diffmod
    data_dict[(condition_name,run_name)] = ujson.loads(json_str) # A data dict for each gene.
ValueError: Expected object or value

Please let me know if I can add any more information or if I should contact by e-mail with any data. Thank you in advance.

**Comment by ploy-np** [comment]
Hi @Wardale24,

Can you provide the xpore dataprep command you used?

**Comment by Wardale24** [comment]
Hi @ploy-np,

The command used was:

xpore dataprep
--eventalign eventalign.txt
--gtf_path_or_url zf.gtf
--transcript_fasta_paths_or_urls zf_cdna.fa
--out_dir dataprep
--genome

Prior to that, reads were mapped to cdna file using minimap2 with the parameters found on your Data preparation from raw reads, followed by:

nanopolish eventalign --reads zf.fastq
--bam zf.bam
-- genome zf_cdna.fa
--signal-index
--scale-events
--summary summary.txt
--threads 32 > eventalign.txt

The .json file in dataprep/ contains some NNNNNs.

Hope this helps find the issue, thank you!

**Comment by ploy-np** [comment]
@Wardale24, are your raw reads directRNA or cDNA?

**Comment by Wardale24** [comment]
Hi @ploy-np, they are directRNA.

**Comment by ploy-np** [comment]
Hi @Wardale24, 

It's strange that the NNNNNs exist in the data.json file. Can you observe any ionic current data points for those NNNNNs?

**Comment by Wardale24** [comment]
I am closing this issue, as the NNNNNs k-mers are not present in the .json file, they were present in the nanopolish outputs.

**Comment by Wardale24** [comment]
To add to this issue in case it is of additional help to anyone with similar errors. Some errors can be caused by the dataprep step with nanopolish while creating the eventalign.txt when running in the background with "&" and/or "nohup", interrupting the eventalign.txt file with something that looks like this:


ENSDART00000126749.3	1657	GCTGA	3349902	t	493	84.87	3.774	0.00664	TCAGC	90.48	5.09	-1.00	154488	154508
ENSDART00000126749.3[post-run summary] total reads: 6323080, unparseable: 0, qc fail: 34121, could not calibrate: 6448, no alignment: 1072, bad fast5: 365962
	1657	GCTGA	3349902	t	492	82.00	2.035	0.00531	TCAGC	90.48	5.09	-1.51	154508	154524

This can be seen when running $ tail -n 100 eventalign.txt.

To avoid this issue, run without "&" and "nohup" and check the tail of your eventalign files to confirm no post-run summary interruptions.
